# @package __global__

model:
  # instansiation related
  model_class_name: se_dual_ae

  encoder_model: demucs_encoder
  decoder_model: demucs_decoder
  feature_model: blstm_feature

  # general
  include_skips_in_fw_pass: true

  # modules related
  demucs:
    chin: 1
    chout: 1
    hidden: 48
    depth: 5
    kernel_size: 8
    stride: 4
    resample: 4
    causal: false
    growth: 2
    max_hidden: 10000
    normalize: true
    rescale: 0.1
    floor: 1e-3


  wav2vec_encoder:
  #  encoder_layers: 6
    encoder_layers: 12

  hifi_gan_generator:
    input_channels: 768
    upsample_initial_channel: 256

  feature_encoder:
    window_size: 5
    hidden_size: 512
  
  include_quantizer: false
  quantizer_name: rvq

  rvq:
    dimension: 768
    n_q: 8
    q_dropout: false
    bins: 1024
    decay: 0.99
    kmeans_init: true
    kmeans_iters: 10
    threshold_ema_dead_code: 2
    orthogonal_reg_weight: 0.0
    orthogonal_reg_active_codes_only: false
    orthogonal_reg_max_codes: # optional, leave blank for default = None