# @package __global__
solver:
  solver: se

  checkpoint:
    continue_from: null
    save_last: true
    save_every: null
    keep_last: null
    keep_every_states: null

  valid:
    every: 1

  generate:
    every: null
    path: 'samples'
    audio:
      format: 'mp3'
      strategy: 'clip'
    lm:
      unconditional_samples: 0
      max_prompt_len: null
      max_gen_len: 256
      use_sampling: false
      temp: 1.0
      top_k: 0
      top_p: 0.0
      remove_prompts: false

  evaluate:
    every: null
    num_workers: 5
    metrics:
      visqol: false
      sisnr: false

  metrics:
    pesq:
      include: true
    stoi:
      include: true
    snr:
      include: true
    visqol:
      mode: audio
      bin: null # /checkpoint/defossez/projects/encodec/visqol
      model: tcdaudio14_aacvopus_coresv_svrnsim_n.68_g.01_c1.model # visqol v3

  optim:
    epochs: 500
    updates_per_epoch: null

    lr: 1e-4
    optimizer: adam

    adam:
      betas: [0.9, 0.999]
      weight_decay: 0.

  schedule:
    lr_scheduler: null
    step:
      step_size: null
      gamma: null
    plateau:
      factor: null
      patience: null
    exponential:
      lr_decay: null
    cosine:
      warmup: null
      lr_min_ratio: 0.0
      cycle_length: 1.0
    polynomial_decay:
      warmup: null
      zero_lr_warmup_steps: 0
      end_lr: 0.0
      power: 1