# @package __global__
# Author: Or Tal.
loss:
  loss_name: naive_se_loss # in sup_se_loss/sup_se_loss/naive_se_loss

  just_reconstruction: False
  reconstruction_factor: 1
  contrastive_factor: 1
  noise_regularization_factor: 10
  stft_sc_factor: 0.1
  stft_mag_factor: 0.1
  include_regularization: True
  include_contrastive: True
  window_size: ${model.feature_encoder.window_size}
